# Generated by Django 4.2.2 on 2023-07-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchwerpunktOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchwerpunktTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Turnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_index', models.CharField(max_length=255)),
                ('kid_vorname', models.CharField(max_length=255)),
                ('kid_nachname', models.CharField(max_length=255)),
                ('geschwister', models.CharField(max_length=255, null=True)),
                ('zeltwunsch', models.CharField(max_length=255, null=True)),
                ('schimmkenntnisse', models.CharField(max_length=255, null=True)),
                ('haftpflichtversicherung', models.CharField(max_length=255, null=True)),
                ('budo_erfahrung', models.BooleanField(null=True)),
                ('anmerkung', models.CharField(max_length=255, null=True)),
                ('anmelder_vorname', models.CharField(max_length=255)),
                ('anmelder_nachname', models.CharField(max_length=255)),
                ('anmelde_organisation', models.CharField(max_length=255, null=True)),
                ('anmelder_mobil', models.CharField(max_length=255, null=True)),
                ('hauptversichert_bei', models.CharField(max_length=255, null=True)),
                ('rechnungsadresse', models.CharField(max_length=255)),
                ('rechnung_ort', models.CharField(max_length=255)),
                ('rechnung_land', models.CharField(max_length=255)),
                ('notfall_kontakte', models.CharField(max_length=255, null=True)),
                ('sozialversicherungsnr', models.CharField(max_length=255, null=True)),
                ('tetanusimpfung', models.CharField(max_length=255, null=True)),
                ('zeckenimpfung', models.CharField(max_length=255, null=True)),
                ('vegetarisch', models.CharField(max_length=255, null=True)),
                ('special_food_description', models.CharField(max_length=255, null=True)),
                ('drugs', models.CharField(max_length=255, null=True)),
                ('illness', models.CharField(max_length=255, null=True)),
                ('rezeptfreie_medikamente', models.CharField(max_length=255, null=True)),
                ('rezept_medikamente', models.CharField(max_length=255, null=True)),
                ('covid', models.CharField(max_length=255, null=True)),
                ('late_anreise', models.DateField(null=True)),
                ('early_abreise_date', models.DateField(null=True)),
                ('early_abreise_abholer', models.CharField(max_length=255, null=True)),
                ('early_abreise_reason', models.CharField(max_length=255, null=True)),
                ('came_back', models.DateField(null=True)),
                ('swp1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.schwerpunktone')),
                ('swp2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.schwerpunkttwo')),
                ('turnus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.turnus')),
            ],
        ),
    ]
