# Generated by Django 4.2.2 on 2023-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='top_jugendticket',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
