# Generated by Django 4.2.2 on 2023-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schwerpunktone',
            name='swp_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schwerpunkttwo',
            name='swp_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turnus',
            name='dateTimeOfUpload',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turnus',
            name='turnus_nr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnus',
            name='uploadedFile',
            field=models.FileField(default='', upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
    ]
