# Generated by Django 4.2.2 on 2023-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0002_kinder_top_jugendticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='sex',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
