# Generated by Django 4.2.2 on 2023-07-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnus',
            name='turnus_nr',
        ),
    ]
