# Generated by Django 4.2.2 on 2023-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0003_kinder_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='kid_alter',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='kid_birthday',
            field=models.DateField(default=None, null=True),
        ),
    ]
