# Generated by Django 4.2.2 on 2023-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0004_kinder_kid_alter_kinder_kid_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='swimmer',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
