# Generated by Django 4.2.2 on 2023-07-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0004_remove_turnus_turnus_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='anmelder_email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='anwesend',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='rechnung_plz',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='turnus_dauer',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='zug_abreise',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='zug_anreise',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='turnus',
            name='turnus_nr',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='turnus',
            name='turnus_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
