# Generated by Django 4.2.2 on 2023-07-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0005_kinder_anmelder_email_kinder_anwesend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schwerpunktone',
            old_name='swp_name',
            new_name='swp_one_name',
        ),
        migrations.RenameField(
            model_name='schwerpunkttwo',
            old_name='swp_name',
            new_name='swp_two_name',
        ),
        migrations.AddField(
            model_name='schwerpunktone',
            name='swp_one_auslagern',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='schwerpunkttwo',
            name='swp_two_auslagern',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
