# Generated by Django 4.2.2 on 2023-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0005_kinder_swimmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='anmerkung_buchung',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='anmerkung_team',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
