# Generated by Django 4.2.2 on 2023-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0006_kinder_anmerkung_buchung_kinder_anmerkung_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
