# Generated by Django 4.2.2 on 2023-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0007_kinder_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung_buchung',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung_team',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='early_abreise_abholer',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='early_abreise_reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='hauptversichert_bei',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='notfall_kontakte',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='zeltwunsch',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
