# Generated by Django 4.2.2 on 2023-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0010_document_remove_kinder_slug_kinder_covid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='budo_family',
            field=models.CharField(choices=[('S', 'Smallies'), ('M', 'Medis'), ('L', 'Largies'), ('XL', 'X-Largies')], max_length=30, null=True),
        ),
    ]
