# Generated by Django 4.2.2 on 2023-07-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0011_kinder_budo_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='ausweis',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='check_in_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='e_card',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='einverstaendnis_erklaerung',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='kinder',
            name='taschengeld',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='budo_family',
            field=models.CharField(choices=[('S', 'Smallie'), ('M', 'Medi'), ('L', 'Largie'), ('XL', 'X-Largie')], max_length=30, null=True),
        ),
    ]
