# Generated by Django 4.2.2 on 2024-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0012_kinder_ausweis_kinder_check_in_date_kinder_e_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='budo_family',
            field=models.CharField(choices=[('S', 'smallie'), ('M', 'medi'), ('L', 'largie'), ('XL', 'x-largie')], max_length=30, null=True),
        ),
    ]
