# Generated by Django 4.2.2 on 2024-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0014_auslagerorte_schwerpunkte_kinder_schwerpunkt_woche1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schwerpunkte',
            name='welche_woche',
            field=models.CharField(choices=[('Unbekannt', 'Unbekannt'), ('Woche 1', 'Woche 1'), ('Woche 2', 'Woche 2')], default='Unbekannt', max_length=10),
        ),
    ]
