# Generated by Django 4.2.2 on 2024-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0015_alter_schwerpunkte_welche_woche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auslagerorte',
            name='bundesland',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='auslagerorte',
            name='land',
            field=models.CharField(blank=True, default='Österreich', max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='auslagerorte',
            name='ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='auslagerorte',
            name='postleitzahl',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='auslagerorte',
            name='strasse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße'),
        ),
    ]
