# Generated by Django 4.2.2 on 2024-01-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0016_alter_auslagerorte_bundesland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auslagerorte',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung_team',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anwesend',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='ausweis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='budo_family',
            field=models.CharField(blank=True, choices=[('S', 'smallie'), ('M', 'medi'), ('L', 'largie'), ('XL', 'x-largie')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='came_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='check_in_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='e_card',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='early_abreise_abholer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='early_abreise_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='early_abreise_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='einverstaendnis_erklaerung',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='late_anreise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='schwerpunkt_woche1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinder_woche1', to='budo_app.schwerpunkte', verbose_name='Schwerpunkt Woche 1'),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='schwerpunkt_woche2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinder_woche2', to='budo_app.schwerpunkte', verbose_name='Schwerpunkt Woche 2'),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='swp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.schwerpunktone'),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='swp2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.schwerpunkttwo'),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='taschengeld',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
