# Generated by Django 4.2.2 on 2024-01-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0018_remove_kinder_swp1_remove_kinder_swp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='covid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='drugs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='illness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='rezept_medikamente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='rezeptfreie_medikamente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='sex',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='sozialversicherungsnr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='special_food_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='swimmer',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='tetanusimpfung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='vegetarisch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='zeckenimpfung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
