# Generated by Django 4.2.2 on 2024-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0019_alter_kinder_covid_alter_kinder_drugs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinder',
            options={'verbose_name_plural': 'Kinder'},
        ),
        migrations.AlterModelOptions(
            name='turnus',
            options={'verbose_name_plural': 'Turnus'},
        ),
        migrations.AddField(
            model_name='schwerpunkte',
            name='auslagern',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
