# Generated by Django 4.2.2 on 2024-01-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0020_alter_kinder_options_alter_turnus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auslagerorte',
            options={'verbose_name_plural': 'Auslagerorte'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='schwerpunkte',
            options={'verbose_name_plural': 'Schwerpunkte'},
        ),
    ]
