# Generated by Django 4.2.2 on 2024-01-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0021_alter_auslagerorte_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchwerpunktOne',
        ),
        migrations.DeleteModel(
            name='SchwerpunktTwo',
        ),
    ]
