# Generated by Django 4.2.2 on 2024-01-12 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budo_app', '0022_delete_schwerpunktone_delete_schwerpunkttwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='budo_family',
            field=models.CharField(blank=True, choices=[('S', 'Smallie'), ('M', 'Medi'), ('L', 'Largie'), ('XL', 'X-largie')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Notizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notiz', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizen', to='budo_app.kinder')),
            ],
        ),
    ]
