# Generated by Django 4.2.2 on 2024-01-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0024_alter_notizen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung_buchung',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
