# Generated by Django 4.2.2 on 2024-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0025_alter_kinder_anmerkung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='wo',
            field=models.CharField(blank=True, choices=[('BuDo', 'BuDo'), ('Sallingstadt', 'Sallingstadt'), ('Krankenhaus', 'Krankenhaus'), ('Auslagern', 'Auslagern'), ('Sonstiges', 'Sonstiges')], default=None, max_length=20, null=True),
        ),
    ]
