# Generated by Django 4.2.2 on 2024-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0029_remove_turnus_turnus_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnus',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
