# Generated by Django 4.2.2 on 2024-04-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0030_alter_turnus_datetimeofupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinder',
            name='kid_alter',
        ),
    ]
