# Generated by Django 4.2.2 on 2024-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0032_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='essen',
            field=models.CharField(blank=True, choices=[('ft', 'Flexitarisch'), ('vt', 'Vegetarisch'), ('vn', 'Vegan')], default='ft', help_text='Was möchtest du essen?', max_length=2),
        ),
    ]
