# Generated by Django 4.2.2 on 2024-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0033_profil_essen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='turnus',
            field=models.ManyToManyField(blank=True, related_name='teamer', to='budo_app.turnus'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rolle',
            field=models.CharField(blank=True, choices=[('b', 'Betreuer:in'), ('k', 'Küche'), ('o', 'Organisator'), ('f', 'Freiwillige:r')], default='b', help_text='Was ist deine Rolle im Team?', max_length=1),
        ),
    ]
