# Generated by Django 4.2.2 on 2024-05-04 17:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0034_profil_turnus_alter_profil_rolle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='telefonnummer',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
