# Generated by Django 4.2.2 on 2024-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0035_profil_telefonnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schwerpunkte',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='betreuende',
            field=models.ManyToManyField(blank=True, related_name='swp', to='budo_app.profil'),
        ),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Wo findet der Schwerpunkt statt?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.auslagerorte'),
        ),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='swp_name',
            field=models.CharField(help_text='Was ist der Name des Schwerpunkts?', max_length=255, verbose_name='Schwerpunktname'),
        ),
        migrations.CreateModel(
            name='Schwerpunktzeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woche', models.CharField(choices=[('w1', 'Woche 1'), ('w2', 'Woche 2')], default='w1', max_length=2, unique=True)),
                ('swp_beginn', models.DateField()),
                ('dauer', models.IntegerField(choices=[(1, 'superkurz'), (2, 'kurz'), (3, 'lang'), (4, 'superlang')])),
                ('turnus', models.ForeignKey(help_text='In welchem Turnus findet dieser Schwerpunkt statt?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budo_app.turnus')),
            ],
        ),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='welche_woche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swp', to='budo_app.schwerpunktzeit'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_choice', models.CharField(choices=[('box', 'Box'), ('budo', 'Im BuDo'), ('warm', 'Warm geliefert')], max_length=10)),
                ('schwerpunkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='budo_app.schwerpunkte')),
            ],
            options={
                'unique_together': {('schwerpunkt', 'day', 'meal_type')},
            },
        ),
    ]
