# Generated by Django 4.2.2 on 2024-05-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0037_rename_welche_woche_schwerpunkte_schwerpunktzeit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schwerpunkte',
            name='Schwerpunktzeit',
        ),
        migrations.AddField(
            model_name='schwerpunkte',
            name='zeit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swp', to='budo_app.schwerpunktzeit'),
        ),
    ]
