# Generated by Django 4.2.2 on 2024-05-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0038_remove_schwerpunkte_schwerpunktzeit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schwerpunkte',
            old_name='zeit',
            new_name='schwerpunktzeit',
        ),
    ]
