# Generated by Django 4.2.2 on 2024-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0040_alter_schwerpunktzeit_woche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('budo', 'Im BuDo'), ('warm', 'Warm geliefert')], max_length=10),
        ),
    ]
