# Generated by Django 4.2.2 on 2024-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0043_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='schwerpunkte',
            field=models.ManyToManyField(blank=True, related_name='swp_kinder', to='budo_app.schwerpunkte', verbose_name='Schwerpunkt'),
        ),
    ]
