# Generated by Django 4.2.2 on 2024-05-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0044_kinder_schwerpunkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinder',
            name='schwerpunkt_woche1',
        ),
        migrations.RemoveField(
            model_name='kinder',
            name='schwerpunkt_woche2',
        ),
    ]
