# Generated by Django 4.2.2 on 2024-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0045_remove_kinder_schwerpunkt_woche1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auslagerorte',
            name='maps_link_parkspot',
            field=models.URLField(blank=True, verbose_name='Google Maps Link Parkspot'),
        ),
    ]
