# Generated by Django 4.2.2 on 2024-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0046_auslagerorte_maps_link_parkspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='notiz_abreise',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
