# Generated by Django 4.2.2 on 2024-05-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0047_kinder_notiz_abreise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='turnus',
        ),
        migrations.AddField(
            model_name='profil',
            name='turnus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamer', to='budo_app.turnus'),
        ),
    ]
