# Generated by Django 4.2.2 on 2024-05-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0048_remove_profil_turnus_profil_turnus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schwerpunkte',
            name='schwerpunktzeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swp', to='budo_app.schwerpunktzeit'),
        ),
        migrations.AlterField(
            model_name='schwerpunktzeit',
            name='dauer',
            field=models.IntegerField(choices=[(1, '1 Tag - superkurz'), (2, '2 Tage - kurz'), (3, '3 Tage - lang'), (4, '4 Tage - superlang')]),
        ),
    ]
