# Generated by Django 4.2.2 on 2024-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0051_alter_schwerpunktzeit_turnus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auslagerorte',
            name='kontakt',
            field=models.TextField(blank=True),
        ),
    ]
