# Generated by Django 5.0.6 on 2024-07-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0053_geld'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuslagerorteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auslagerorte_images/')),
                ('auslagerort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='budo_app.auslagerorte')),
            ],
        ),
    ]
