# Generated by Django 5.0.6 on 2024-07-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0055_auslagerortenotizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchwerpunktWahl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dritte_wahl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dritte_wahl', to='budo_app.schwerpunkte')),
                ('erste_wahl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erste_wahl', to='budo_app.schwerpunkte')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schwerpunkt_wahl', to='budo_app.kinder')),
                ('schwerpunktzeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wahlen', to='budo_app.schwerpunktzeit')),
                ('zweite_wahl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zweite_wahl', to='budo_app.schwerpunkte')),
            ],
            options={
                'verbose_name': 'Schwerpunkt Wahl',
                'verbose_name_plural': 'Schwerpunkt Wahlen',
                'unique_together': {('kind', 'schwerpunktzeit')},
            },
        ),
    ]
