# Generated by Django 5.0.6 on 2024-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0056_schwerpunktwahl'),
    ]

    operations = [
        migrations.AddField(
            model_name='schwerpunktwahl',
            name='freunde',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
