# Generated by Django 5.0.6 on 2024-07-09 10:06

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0057_schwerpunktwahl_freunde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auslagerorteimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=0.5, size=[1080, 1080], upload_to='auslagerorte_images/'),
        ),
    ]
