# Generated by Django 5.0.6 on 2024-07-09 11:47

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0058_alter_auslagerorteimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='coffee',
            field=models.CharField(blank=True, default='', help_text='Wie magst du deinen Kaffee?', max_length=500),
        ),
        migrations.AlterField(
            model_name='auslagerorteimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=True, quality=75, scale=None, size=[1080, 1080], upload_to='auslagerorte_images/'),
        ),
    ]
