# Generated by Django 5.0.6 on 2024-07-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0059_profil_coffee_alter_auslagerorteimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpezialFamilien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('turnus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spezial_familien', to='budo_app.turnus')),
            ],
        ),
        migrations.AddField(
            model_name='kinder',
            name='spezial_familien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinder', to='budo_app.spezialfamilien'),
        ),
    ]
