# Generated by Django 5.0.6 on 2024-07-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0060_spezialfamilien_kinder_spezial_familien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spezialfamilien',
            options={'verbose_name_plural': 'Spezialfamilien'},
        ),
    ]
