# Generated by Django 5.1.3 on 2025-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0063_alter_betreuerinnengeld_who'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['turnus'], name='kinder_turnus_idx'),
        ),
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['kid_index'], name='kinder_kid_index_idx'),
        ),
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['anwesend'], name='kinder_anwesend_idx'),
        ),
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['turnus', 'anwesend'], name='kinder_turnus_anwesend_idx'),
        ),
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['budo_family'], name='kinder_budo_family_idx'),
        ),
        migrations.AddIndex(
            model_name='kinder',
            index=models.Index(fields=['kid_vorname', 'kid_nachname'], name='kinder_name_idx'),
        ),
        migrations.AddIndex(
            model_name='schwerpunkte',
            index=models.Index(fields=['schwerpunktzeit'], name='schwerpunkte_zeit_idx'),
        ),
        migrations.AddIndex(
            model_name='schwerpunkte',
            index=models.Index(fields=['ort'], name='schwerpunkte_ort_idx'),
        ),
        migrations.AddIndex(
            model_name='schwerpunkte',
            index=models.Index(fields=['auslagern'], name='schwerpunkte_auslagern_idx'),
        ),
        migrations.AddIndex(
            model_name='turnus',
            index=models.Index(fields=['turnus_beginn'], name='turnus_beginn_idx'),
        ),
        migrations.AddIndex(
            model_name='turnus',
            index=models.Index(fields=['turnus_nr'], name='turnus_nr_idx'),
        ),
    ]
