# Generated by Django 5.1.3 on 2025-07-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0064_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='notfall_kontakte',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
