# Generated by Django 5.1.3 on 2025-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0065_alter_kinder_notfall_kontakte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='anmerkung_buchung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kinder',
            name='notfall_kontakte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
