# Generated by Django 5.1.3 on 2025-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0067_alter_kinder_drugs_alter_kinder_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinder',
            name='pfand',
            field=models.IntegerField(default=0),
        ),
    ]
