# Generated by Django 5.2.16 on 2026-07-17 15:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0068_kinder_pfand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auslagerorteimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1080, 1080], upload_to='auslagerorte_images/'),
        ),
    ]
