# Generated by Django 5.2.16 on 2026-07-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0069_alter_auslagerorteimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=40)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_label', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
                ('details', models.JSONField(default=dict)),
                ('turnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='budo_app.turnus')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'permissions': (('export_auditevent', 'Can export audit events'),),
                'indexes': [models.Index(fields=['turnus', '-occurred_at', '-id'], name='audit_turnus_time_idx'), models.Index(fields=['turnus', 'action'], name='audit_turnus_action_idx'), models.Index(fields=['turnus', 'resource_type', 'resource_id'], name='audit_resource_idx')],
            },
        ),
    ]
