# Generated by Django 5.2.16 on 2026-07-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0070_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('has_operational_activity', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('display_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HappyCleaningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HappyCleaningStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_kids', models.PositiveIntegerField()),
                ('meeting_point', models.CharField(max_length=500)),
                ('wishes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('has_ever_had_assignment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HappyCleaningTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='kinder',
            name='happy_cleaning_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='kinder',
            constraint=models.CheckConstraint(condition=models.Q(('happy_cleaning_number__isnull', True), ('happy_cleaning_number__gt', 0), _connector='OR'), name='kinder_hc_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='kinder',
            constraint=models.UniqueConstraint(condition=models.Q(('happy_cleaning_number__isnull', False)), fields=('turnus', 'happy_cleaning_number'), name='kinder_turnus_hc_number_uniq'),
        ),
        migrations.AddField(
            model_name='happycleaning',
            name='turnus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_cleanings', to='budo_app.turnus'),
        ),
        migrations.AddField(
            model_name='happycleaningassignment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_cleaning_assignments', to='budo_app.kinder'),
        ),
        migrations.AddField(
            model_name='happycleaningassignment',
            name='happy_cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budo_app.happycleaning'),
        ),
        migrations.AddField(
            model_name='happycleaningstation',
            name='happy_cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='budo_app.happycleaning'),
        ),
        migrations.AddField(
            model_name='happycleaningstation',
            name='responsible_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happy_cleaning_stations', to='budo_app.profil'),
        ),
        migrations.AddField(
            model_name='happycleaningassignment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budo_app.happycleaningstation'),
        ),
        migrations.AddField(
            model_name='happycleaningtodo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='budo_app.happycleaningstation'),
        ),
        migrations.AddConstraint(
            model_name='happycleaning',
            constraint=models.CheckConstraint(condition=models.Q(('display_number__gt', 0)), name='happy_cleaning_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaning',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='happy_cleaning_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaning',
            constraint=models.UniqueConstraint(fields=('turnus', 'display_number'), name='happy_cleaning_turnus_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningstation',
            constraint=models.CheckConstraint(condition=models.Q(('max_kids__gt', 0)), name='hc_station_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningstation',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='hc_station_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningstation',
            constraint=models.UniqueConstraint(fields=('happy_cleaning', 'position'), name='hc_station_event_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningassignment',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='hc_assignment_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningassignment',
            constraint=models.UniqueConstraint(fields=('happy_cleaning', 'child'), name='hc_assignment_event_child_uniq'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningtodo',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='hc_todo_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningtodo',
            constraint=models.UniqueConstraint(fields=('station', 'position'), name='hc_todo_station_position_uniq'),
        ),
    ]
