# Generated by Django 5.2.16 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budo_app", "0071_happy_cleaning_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="HappyCleaningCommandRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.BigIntegerField()),
                ("request_id", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="happy_cleaning_command_requests",
                        to="budo_app.turnus",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="happycleaningcommandrequest",
            constraint=models.UniqueConstraint(
                fields=("turnus", "actor_id", "request_id"),
                name="hc_command_actor_request_uniq",
            ),
        ),
    ]
