# Generated by Django 5.2.16 on 2026-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0073_kinder_happy_cleaning_number_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='budo_family',
            field=models.CharField(blank=True, choices=[('S', 'Smallie'), ('M', 'Medi'), ('L', 'Largie'), ('XL', 'X-largie')], default='', max_length=2, verbose_name='BuDo-Familie'),
        ),
    ]
