# Generated by Django 5.2.16 on 2026-07-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0074_profil_budo_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErsteHilfeEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erste_hilfe_eintraege', to='budo_app.kinder')),
            ],
            options={
                'verbose_name': 'EH-Eintrag',
                'verbose_name_plural': 'EH-Einträge',
            },
        ),
    ]
