# Generated by Django 5.2.16 on 2026-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0076_entry_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schwerpunkte',
            name='geplante_abreise',
        ),
        migrations.RemoveField(
            model_name='schwerpunkte',
            name='geplante_ankunft',
        ),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='auslagern',
            field=models.BooleanField(default=False),
        ),
    ]
