# Generated by Django 5.2.16 on 2026-07-21 14:30

from django.db import migrations, models


def fill_missing_auslagern(apps, schema_editor):
    Schwerpunkte = apps.get_model('budo_app', 'Schwerpunkte')
    Schwerpunkte.objects.filter(auslagern__isnull=True).update(auslagern=False)


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0076_entry_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schwerpunkte',
            name='geplante_abreise',
        ),
        migrations.RemoveField(
            model_name='schwerpunkte',
            name='geplante_ankunft',
        ),
        migrations.RunPython(fill_missing_auslagern, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='schwerpunkte',
            name='auslagern',
            field=models.BooleanField(default=False),
        ),
    ]
