# Generated by Django 5.2.16 on 2026-07-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0078_auslagerorteimage_notiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='happycleaningassignment',
            name='target_kind',
            field=models.CharField(choices=[('station', 'Station'), ('excused', 'Entschuldigt')], default='station', max_length=16),
        ),
        migrations.AlterField(
            model_name='happycleaningassignment',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budo_app.happycleaningstation'),
        ),
        migrations.AddConstraint(
            model_name='happycleaningassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('station__isnull', False), ('target_kind', 'station')), models.Q(('station__isnull', True), ('target_kind', 'excused')), _connector='OR'), name='hc_assignment_target_valid'),
        ),
    ]
