# Generated by Django 5.2.16 on 2026-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budo_app", "0082_allow_zero_happy_cleaning_station_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="happycleaningcommandrequest",
            name="fingerprint",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="happycleaningcommandrequest",
            name="status_code",
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="kinder",
            name="edit_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="happycleaningcommandrequest",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(action="kid.edit")
                    | models.Q(fingerprint__isnull=False)
                ),
                name="hc_kid_edit_fingerprint_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="kinder",
            constraint=models.CheckConstraint(
                condition=models.Q(edit_version__gt=0),
                name="kinder_edit_version_positive",
            ),
        ),
    ]
