# Generated by Django 5.2.16 on 2026-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0084_kinder_checkout_notiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auslagerorte',
            name='maps_link',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Google Maps Link'),
        ),
        migrations.AlterField(
            model_name='auslagerorte',
            name='maps_link_parkspot',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Google Maps Link Parkspot'),
        ),
    ]
