# Generated by Django 5.2.16 on 2026-08-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0088_tag_icons_and_primary_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(choices=[('map-pin', 'Ort'), ('tent-tree', 'Zeltplatz'), ('house', 'Haus'), ('warehouse', 'Halle'), ('trees', 'Wald'), ('mountain', 'Berg'), ('waves', 'Wasser'), ('castle', 'Burg'), ('utensils', 'Essen'), ('bed', 'Übernachtung'), ('bus', 'Bus'), ('accessibility', 'Barrierefrei'), ('building-2', 'Gebäude'), ('school', 'Schule'), ('church', 'Kirche'), ('landmark', 'Sehenswürdigkeit'), ('factory', 'Betrieb'), ('store', 'Geschäft'), ('shopping-cart', 'Einkaufen'), ('hospital', 'Krankenhaus'), ('cross', 'Erste Hilfe'), ('stethoscope', 'Arzt'), ('heart-pulse', 'Gesundheit'), ('shield-plus', 'Sicherheit'), ('toilet', 'Toilette'), ('shower-head', 'Dusche'), ('bath', 'Bad'), ('washing-machine', 'Waschmöglichkeit'), ('cooking-pot', 'Küche'), ('coffee', 'Café'), ('cup-soda', 'Getränke'), ('ice-cream-bowl', 'Eis'), ('sandwich', 'Jause'), ('pizza', 'Pizza'), ('apple', 'Obst'), ('car', 'Auto'), ('train-front', 'Bahn'), ('bike', 'Fahrrad'), ('ship', 'Schiff'), ('plane', 'Flugzeug'), ('circle-parking', 'Parkplatz'), ('route', 'Route'), ('signpost', 'Wegweiser'), ('traffic-cone', 'Straßensperre'), ('tree-pine', 'Nadelwald'), ('flower-2', 'Blumen'), ('leaf', 'Natur'), ('sprout', 'Garten'), ('sun', 'Sonne'), ('cloud-sun', 'Wechselhaft'), ('cloud-rain', 'Regen'), ('snowflake', 'Schnee'), ('wind', 'Wind'), ('footprints', 'Fußweg'), ('dumbbell', 'Fitness'), ('goal', 'Sportplatz'), ('trophy', 'Wettbewerb'), ('medal', 'Turnier'), ('gamepad-2', 'Spiele'), ('puzzle', 'Rätsel'), ('dice-5', 'Würfelspiel'), ('music', 'Musik'), ('guitar', 'Gitarre'), ('drama', 'Theater'), ('palette', 'Kreativ'), ('paintbrush', 'Malen'), ('book-open', 'Lesen'), ('library', 'Bibliothek'), ('binoculars', 'Aussicht'), ('camera', 'Fotopunkt'), ('circle-help', 'Unbekannt'), ('info', 'Information'), ('badge-alert', 'Hinweis'), ('triangle-alert', 'Gefahr'), ('shield', 'Geschützt'), ('lock-keyhole', 'Versperrt'), ('key-round', 'Schlüssel'), ('flashlight', 'Taschenlampe'), ('radio', 'Funk'), ('wifi', 'WLAN'), ('phone', 'Telefon'), ('battery-charging', 'Strom'), ('clock', 'Uhrzeit'), ('calendar-days', 'Termin'), ('sunrise', 'Sonnenaufgang'), ('sunset', 'Sonnenuntergang'), ('moon', 'Nacht'), ('star', 'Favorit'), ('heart', 'Herz'), ('users', 'Gruppe'), ('dog', 'Hund'), ('bird', 'Vogel'), ('fish', 'Fisch'), ('anchor', 'Anlegestelle'), ('fence', 'Zaun'), ('flame-kindling', 'Lagerfeuer'), ('person-standing', 'Treffpunkt'), ('activity', 'Aktivität'), ('paw-print', 'Tiere'), ('navigation', 'Navigation')], default='map-pin', max_length=40),
        ),
    ]
