# Generated by Django 5.2.16 on 2026-08-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budo_app', '0098_enforce_unique_nonblank_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinder',
            name='spezial_familien',
        ),
        migrations.DeleteModel(
            name='SpezialFamilien',
        ),
    ]
