import { useMemo, useState } from 'react';
import {
  MapPinIcon,
  TentTreeIcon,
  HouseIcon,
  WarehouseIcon,
  TreesIcon,
  MountainIcon,
  WavesIcon,
  CastleIcon,
  UtensilsIcon,
  BedIcon,
  BusIcon,
  AccessibilityIcon,
  Building2Icon,
  SchoolIcon,
  ChurchIcon,
  LandmarkIcon,
  FactoryIcon,
  StoreIcon,
  ShoppingCartIcon,
  HospitalIcon,
  CrossIcon,
  StethoscopeIcon,
  HeartPulseIcon,
  ShieldPlusIcon,
  ToiletIcon,
  ShowerHeadIcon,
  BathIcon,
  WashingMachineIcon,
  CookingPotIcon,
  CoffeeIcon,
  CupSodaIcon,
  IceCreamBowlIcon,
  SandwichIcon,
  PizzaIcon,
  AppleIcon,
  CarIcon,
  TrainFrontIcon,
  BikeIcon,
  ShipIcon,
  PlaneIcon,
  CircleParkingIcon,
  RouteIcon,
  SignpostIcon,
  TrafficConeIcon,
  TreePineIcon,
  Flower2Icon,
  LeafIcon,
  SproutIcon,
  SunIcon,
  CloudSunIcon,
  CloudRainIcon,
  SnowflakeIcon,
  WindIcon,
  FootprintsIcon,
  DumbbellIcon,
  GoalIcon,
  TrophyIcon,
  MedalIcon,
  Gamepad2Icon,
  PuzzleIcon,
  Dice5Icon,
  MusicIcon,
  GuitarIcon,
  DramaIcon,
  PaletteIcon,
  PaintbrushIcon,
  BookOpenIcon,
  LibraryIcon,
  BinocularsIcon,
  CameraIcon,
  CircleHelpIcon,
  InfoIcon,
  BadgeAlertIcon,
  TriangleAlertIcon,
  ShieldIcon,
  LockKeyholeIcon,
  KeyRoundIcon,
  FlashlightIcon,
  RadioIcon,
  WifiIcon,
  PhoneIcon,
  BatteryChargingIcon,
  ClockIcon,
  CalendarDaysIcon,
  SunriseIcon,
  SunsetIcon,
  MoonIcon,
  StarIcon,
  HeartIcon,
  UsersIcon,
  DogIcon,
  BirdIcon,
  FishIcon,
  AnchorIcon,
  FenceIcon,
  FlameKindlingIcon,
  PersonStandingIcon,
  ActivityIcon,
  PawPrintIcon,
  NavigationIcon,
} from 'lucide-react';

import { Button } from './ui/button';
import { Input } from './ui/input';

const settingsTagIcons = {
  'map-pin': MapPinIcon,
  'tent-tree': TentTreeIcon,
  'house': HouseIcon,
  'warehouse': WarehouseIcon,
  'trees': TreesIcon,
  'mountain': MountainIcon,
  'waves': WavesIcon,
  'castle': CastleIcon,
  'utensils': UtensilsIcon,
  'bed': BedIcon,
  'bus': BusIcon,
  'accessibility': AccessibilityIcon,
  'building-2': Building2Icon,
  'school': SchoolIcon,
  'church': ChurchIcon,
  'landmark': LandmarkIcon,
  'factory': FactoryIcon,
  'store': StoreIcon,
  'shopping-cart': ShoppingCartIcon,
  'hospital': HospitalIcon,
  'cross': CrossIcon,
  'stethoscope': StethoscopeIcon,
  'heart-pulse': HeartPulseIcon,
  'shield-plus': ShieldPlusIcon,
  'toilet': ToiletIcon,
  'shower-head': ShowerHeadIcon,
  'bath': BathIcon,
  'washing-machine': WashingMachineIcon,
  'cooking-pot': CookingPotIcon,
  'coffee': CoffeeIcon,
  'cup-soda': CupSodaIcon,
  'ice-cream-bowl': IceCreamBowlIcon,
  'sandwich': SandwichIcon,
  'pizza': PizzaIcon,
  'apple': AppleIcon,
  'car': CarIcon,
  'train-front': TrainFrontIcon,
  'bike': BikeIcon,
  'ship': ShipIcon,
  'plane': PlaneIcon,
  'circle-parking': CircleParkingIcon,
  'route': RouteIcon,
  'signpost': SignpostIcon,
  'traffic-cone': TrafficConeIcon,
  'tree-pine': TreePineIcon,
  'flower-2': Flower2Icon,
  'leaf': LeafIcon,
  'sprout': SproutIcon,
  'sun': SunIcon,
  'cloud-sun': CloudSunIcon,
  'cloud-rain': CloudRainIcon,
  'snowflake': SnowflakeIcon,
  'wind': WindIcon,
  'footprints': FootprintsIcon,
  'dumbbell': DumbbellIcon,
  'goal': GoalIcon,
  'trophy': TrophyIcon,
  'medal': MedalIcon,
  'gamepad-2': Gamepad2Icon,
  'puzzle': PuzzleIcon,
  'dice-5': Dice5Icon,
  'music': MusicIcon,
  'guitar': GuitarIcon,
  'drama': DramaIcon,
  'palette': PaletteIcon,
  'paintbrush': PaintbrushIcon,
  'book-open': BookOpenIcon,
  'library': LibraryIcon,
  'binoculars': BinocularsIcon,
  'camera': CameraIcon,
  'circle-help': CircleHelpIcon,
  'info': InfoIcon,
  'badge-alert': BadgeAlertIcon,
  'triangle-alert': TriangleAlertIcon,
  'shield': ShieldIcon,
  'lock-keyhole': LockKeyholeIcon,
  'key-round': KeyRoundIcon,
  'flashlight': FlashlightIcon,
  'radio': RadioIcon,
  'wifi': WifiIcon,
  'phone': PhoneIcon,
  'battery-charging': BatteryChargingIcon,
  'clock': ClockIcon,
  'calendar-days': CalendarDaysIcon,
  'sunrise': SunriseIcon,
  'sunset': SunsetIcon,
  'moon': MoonIcon,
  'star': StarIcon,
  'heart': HeartIcon,
  'users': UsersIcon,
  'dog': DogIcon,
  'bird': BirdIcon,
  'fish': FishIcon,
  'anchor': AnchorIcon,
  'fence': FenceIcon,
  'flame-kindling': FlameKindlingIcon,
  'person-standing': PersonStandingIcon,
  'activity': ActivityIcon,
  'paw-print': PawPrintIcon,
  'navigation': NavigationIcon,
};

export default function TagIconPicker({ choices, value, onChange, label }) {
  const [query, setQuery] = useState('');
  const visibleChoices = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase('de');
    if (!normalized) return choices;
    return choices.filter(choice => `${choice.label} ${choice.value}`.toLocaleLowerCase('de').includes(normalized));
  }, [choices, query]);

  return <fieldset className="grid gap-2"><legend className="mb-2 text-sm font-medium">{label}</legend><label className="relative block"><span className="sr-only">Symbole suchen</span><Input type="search" placeholder="Symbole suchen…" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="flex max-h-72 flex-wrap content-start gap-2 overflow-y-auto py-1">{visibleChoices.map(choice => {
    const Icon = settingsTagIcons[choice.value] || MapPinIcon;
    return <Button className="size-10 shrink-0" size="icon" variant={value === choice.value ? 'secondary' : 'outline'} type="button" aria-label={choice.label} aria-pressed={value === choice.value} title={choice.label} onClick={() => onChange(choice.value)} key={choice.value}><Icon aria-hidden="true" /></Button>;
  })}{visibleChoices.length === 0 && <p className="text-sm text-muted-foreground">Keine Symbole gefunden.</p>}</div></fieldset>;
}
